esphome:
    name: hpsu-can
    friendly_name: HPSU.CAN
    platformio_options:
        build_unflags:
            - "-std=gnu++11"
            - "-fno-rtti"
        build_flags:
            - "-std=gnu++17"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/Trunks1982/Daikin-Rotex-HPSU-CAN.git
      ref: main   # Replace “main” with “dev” if you want to use the development branch
    refresh: 0s

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

web_server:
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  ap:
    ssid: DaikinRotex Fallback Hotspot
    password: H3jGqANSa7aL

captive_portal:

time:
  - platform: homeassistant

debug:
  update_interval: 5s

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Seconds
  - platform: uptime
    type: timestamp
    name: Uptime Timestamp
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

button:
  - platform: restart
    name: "Rotex ESP Restart"
#switch:
#  - platform: gpio
#    name: Smart Grid
#    pin:
#      number: GPIO06
#      inverted: true

#  - platform: gpio
#    name: EVU
#    pin:
#      number: GPIO05
#      inverted: true

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID

canbus:
  - platform: esp32_can
    id: can_bus
    can_id: 0x680
    tx_pin: GPIO5
    rx_pin: GPIO6
    bit_rate: 20kbps

daikin_rotex_can:
  id: rotext_hpsu
  language: en
  canbus_id: can_bus
  update_interval: 30

  # Some Tv, TvBH, or Tr sensors provide values with deviations.
  # These deviations can be corrected using an offset to improve the accuracy of detecting faulty 3-way valves.
  # For example, if the Tv sensor shows a temperature that is 1.5°C too high, the Tv offset should be set to -1.5.
  # If it provides values that are 1.2°C too low, the offset should be set to 1.2.
  # The same applies to TvBH and Tr.
  #tv_offset: -1.0
  #tvbh_offset: -1.0
  #tr_offset: -1.0

  #max_spread_tvbh_tv: 0.5  # Legt Tv-TVBH-Schwellwert fest, bei dem die DHW-Ventil-Fehler-Erkennung auslösen soll
  #max_spread_tvbh_tr: 0.5  # Legt TVBH-Tr-Schwellwert fest, bei dem die BPV-Ventil-Fehler-Erkennung auslösen soll

  log_filter:
    name: Log Filter
  custom_request:
    name: Custom Request
  dump:
    name: Dump Senors
  project_git_hash:
    name: Project Git Hash
  entities:

# Info

    error_code:
      name: Error Code

    mode_of_operating:
      name: Mode of Operating
    ext:
      name: Ext
# RT
    circulation_pump:
      name: Circulation Pump
# EHS
    bypass_valve:
      name: Bypass Valve
    tv:
      name: Flow Temperature (TV)
      update_interval: 5
    tvbh:
      name: Flow Temperature Heating (TVBH)
      update_interval: 5
    tr:
      name: Return Temperature Heating
      update_interval: 5
    tdhw1:
      name: Hot Water Temperature
    tdhw2:
      name: Hot Water Temperature 2
    temperature_outside:
      name: Outside Temperature
# V
# TVBH2
# TR2
# Tdhw2
    tliq:
      name: Liquid Line Temperature
    ta2:
      name: TA2
# quiet

# Overview
    water_pressure:
      name: Water Pressure
    t_hs:
      name: T-WE
# T-WE Soll
    t_ext:
      name: T-Outside
# T-WW
# T-WW Soll
# T-Rücklauf
    flow_rate:
      name: Flow Rate
      update_interval: 10
# T-HK
# T-HK Soll
    status_kesselpumpe:
      name: Boiler Pump Status
    status_kompressor:
      name: Compressor Status
    runtime_compressor:
      name: Compressor Runtime
    runtime_pump:
      name: Pump Runtime
    dhw_mixer_position:
      name: DHW Mixer Position
    qboh:
      name: EHS for DHW
    ehs_for_ch:
      name: EHS for CH
    energy_cooling:
      name: Cooling Energy
    qch:
      name: Heating Energy
    total_energy_produced:
      name: Total Energy Produced
    qdhw:
      name: Energy for DHW
    total_electrical_energy:
      name: Total Electrical Energy
#WE Typ
#SwNr B1/U1
#SwNr Regler
#SwNr RTXRT

# ESP custom sensors
    energy_saving_mode:
      name: ES Mode

# Betriebsart
    operating_mode:
      name: Operating Mode
      update_interval: 5

# Room Set Day
    target_room1_temperature:
      name: Target Room 1 Temperature
      type: select
# T-RaumSoll 2
# T-RaumSoll 3

# Room Set Night
  # T-Absenkung
  # T-Abwesend

# WW Solltemp
    target_hot_water_temperature:
      name: Target Hot Water Temperature
      type: select

# T-WWSoll 2
# T-WWSoll 3

# WW Install
    dhw_run:
      name: DHW Run
    1_dhw:
      name: 1 x Domestic Hot Water
    hp_hyst_tdhw:
      name: HP Hyst TDHW
    delay_time_for_backup_heating:
      name: Waiting Time for Backup Heating

# Configuration

# Configuration -> Installation
# Sprache
# Datum
    system_date_day:
      name: System Date Day
      internal: true
    system_date_month:
      name: System Date Month
      internal: true
    system_date_year:
      name: System Date Year
      internal: true
    system_date:
      name: System Date
# Uhrzeit
    system_time_hour:
      name: System Time Hour
      internal: true
    system_time_minute:
      name: System Time Minute
      internal: true
    system_time_second:
      name: System Time Second
      internal: true
      update_interval: 1
    system_time:         # This entity causes the HA database to grow rapidly! Please add it to HA -> recorder -> exclude -> entities!
      name: System Time

#...
    outdoor_unit:
      name: Outdoor Unit
    indoor_unit:
      name: Indoor Unit
    function_ehs:
      name: Function EHS
    ch_support:
      name: CH Support
    bivalence_function:
      name: Bivalence Function
    smart_grid:
      name: Smart Grid
    sg_mode:
      name: SG Mode
# HT/NT Funktion
# HT/NT Anschluss
# Raumthermostat
# Interlinkfunktion
# Konfig MFR 1
# Entlüftungsfunktion
# PWM Konfig
    circulation_pump_min:
      name: Circulation Pump Min
    circulation_pump_max:
      name: Circulation Pump Max
# ...
# Sensor Konfig
    external_temp_sensor:
      name: Config External Temperature
    # SKonfig T-WW
    # SKonfig Druck
# AF Anspassung
# Terminal Adresse
# Konfig System

# Configuration -> System Configuration

    power_dhw:
      name: Power DHW
      #type: select
    power_ehs_1:
      name: Power EHS Level 1
    power_ehs_2:
      name: Power EHS Level 2
    power_biv:
      name: Power BIV
    tdiff_dhw_ch:
      name: TDiff DHW CH
    max_heating_temperature:
      name: Max Heating Temperature
    bivalence_temperature:
      name: bivalence point
    quiet:
      name: Silent Mode
#Sonderfunkt Schaltk
#Wartezeit Sonderfunkt
    t_dhw_1_min:
      name: Switch Threshold TDHW
    delta_temp_ch:
      name: CH Spread
    delta_temp_dhw:
      name: DHW Spread
#VerzZeitPumpe                # service
    flow_rate_min:
      name: Flow Rate Min
    flow_rate_setpoint:
      name: Flow Rate Setpoint
    flow_rate_calc:
      name: Flow Rate Calculated
    flow_rate_hyst:
      name: Flow Rate Hysteresis
    supply_temperature_adjustment_heating:
      name: Supply Temperature Adjustment Heating
    supply_temperature_adjustment_cooling:
      name: Supply Temperature Adjustment Cooling
    min_pressure:
      name: Min Pressure
    max_pressure:
      name: Max Pressure
    set_pressure:
      name: Set Pressure
    max_pressure_drop:
      name: Max Pressure Drop
#Relaistest

# Konfiguration -> HZK Konfig
    hk_function:
      name: HK Function
    temperature_antifreeze:
      name: Anti-Freeze Temperature
    building_insulation:
      name: Building Insulation
#Estrich
#Estrichprogramm

# Konfiguration -> HZK Konfig -> Kühlen
    start_t_out_cooling:
      name: Start T-Out Cooling
    max_t_out_cooling:
      name: Max T-Out Cooling
    t_flow_cooling_start:
      name: T-Flow Cooling start
    t_flow_cooling_max:
      name: T-Flow Cooling max
    min_t_flow_cooling:
      name: Min T-Flow Cooling
    t_flow_cooling:
      name: T-Flow Cooling
    t_h_c_switch:
      name: T_H/C Switch
    cooling_setpoint_adj:
      name: Cooling Setpoint adjustment

# Konfiguration -> HZK Konfig -> Heizen

    heating_limit_day:
      name: Heating Limit Day
    heating_limit_night:
      name: Heating Limit Night
    heating_curve:
      name: Heating Curve
#Raumeinfluss
#RF Anpassung
    flow_temperature_day:
      name: Flow Temperature Day
    flow_temperature_night:
      name: Flow Temperature Night
    max_target_flow_temp:
      name: Max Target Flow Temperature
    min_target_flow_temp:
      name: Min Target Flow Temperature
    heating_curve_adaptation:
      name: Heating Curve Adaptation

# Konfiguration -> HZK Konfig -> Kühlen

#StartKühlen A-Temp
#MaxKühlen A-Temp
#VL-SollStartKühlen
#VL-SollMaxKühlen
#MinVL-SollKühlen
#T-VLKühlen
#T_H/K Umschaltung
#KühlsollwertKorr

#Konfiguration -> WW Konfig

    circulation_with_dhw_program:
      name: Circulation with DHW Program
    circulation_interval_on:
      name: Circulation Interval On
    circulation_interval_off:
      name: Circulation Interval Off
    antileg_day:
      name: Anti-Legionella Day
#AntilegZeit
    antileg_temp:
      name: Anti-Legionella Temperature
    max_dhw_loading:
      name: Max DHW Loading Time
    dhw_off_time:
      name: DHW Off Time

# Others

    electric_heater:
      name: Electric Heater - For Pumps After October 2018
    thermal_power:
      name: Thermal Power
    optimized_defrosting:
      name: Optimized Defrosting
    temperature_spread:
      name: Spreizung
    tv_tvbh_delta:
      name: Tv-TVBH Delta
    tvbh_tr_delta:
      name: TVBH-Tr Delta
    vorlauf_soll_tv_delta:
      name: FlowSetpoint-Tv Delta
# Rocon U1

    #t_room:
    #  name: Actual Room Temperature

# To be categorized

    target_supply_temperature:
      name: Target Supply Temperature
    supply_setpoint_regulated:
      name: Flow Setpoint Controlled
